### PR TITLE
Restyle modals

### PR DESCRIPTION
**Pull request by SwenVanZanten**
## Description

Restyled the send panel to improve UX
Added a maximum send button
Restyled the receive panel
Restyled the unlock panel
Restyled the credits panel
Restyled the debug panel

## Screenshots (if appropriate):
schermafbeelding 2018-07-08 om 11 43 01
schermafbeelding 2018-07-08 om 09 35 54
schermafbeelding 2018-07-08 om 09 36 16
schermafbeelding 2018-07-08 om 09 37 33
schermafbeelding 2018-07-08 om 09 35 40
schermafbeelding 2018-07-08 om 09 37 14

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Positivism** [comment]
If you could move balance after send and add [https://github.com/vergecurrency/vWallet/issues/13](https://github.com/vergecurrency/vWallet/issues/13).
<3 I'm still getting used to components even so to make this simple commit.

**Comment by SwenVanZanten** [comment]
How about a button to add the max balance? Cause the “max” balance is right above the send button

**Comment by marpme** [comment]
@HDsign seems to be cool to add a max button for the send panel

**Comment by Positivism** [comment]
@HDsign Max as in balance-transaction fee. Max button would be nice too.

**Comment by Positivism** [comment]
Love this.

**Comment by Positivism** [comment]
Your wallet balance after the transaction:
to
Balance after this transaction:

Just to make it shorter, hate to be nitpicky.

**Comment by SwenVanZanten** [comment]
@Positivism good point!

**Comment by marpme** [comment]
Please remove the **WIP**, so I can review thanks <3

**Comment by SwenVanZanten** [comment]
How does it suddenly wip 🤔

**Comment by marpme** [comment]
Everything looks great, review passed 💯

**Pull request merged**
